version: 0.2
phases:
  install:
    commands:
      - npm i npm@latest -g
      - pip install --upgrade pip
  pre_build:
    commands:
      - echo Pre_build Phase
      # - yarn install
  build:
    commands:
      - echo Build Phase
      # - yarn build
  post_build:
    commands:
      - echo PostBuild Phase

artifacts:
  files:
    - '**/*'
  discard-path: no
  base-directory: build
