version: 0.2
phases:
  install:
    commands:
      - npm npm@latest -g
      - pip install --upgrade pip
      - npm install -g yarn
      - echo yarn -v
      - yarn -v
  pre_build:
    commands:
      - echo Pre_build Phase
      - yarn install
  build:
    commands:
      - echo Build Phase
      - yarn run build
  post_build:
    commands:
      - echo PostBuild Phase

artifacts:
  files:
    - '**/*'
  discard-path: no
  base-directory: build
